config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'openai#index'

  get 'openai', to: 'openai#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/openai_controller.rb
class OpenaiController < ApplicationController
  def index
    return unless params[:query]

    @response = OpenaiService.new(params[:query]).call
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/openai_helper.rb
module OpenaiHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGpt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex">
      <%= yield %>
    </main>
  </body>
</html>

app/views/openai/index.erb
<div class="row">
  <%= form_with url: openai_path, method: :get do |form| %>
    <div class="form-group">
      <%= form.label :query %>
      <%= form.text_area :query %>
      <%= form.submit 'get content' %>
     </div>
  <% end %>
</div>